# Generated by Django 2.2.6 on 2020-04-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(to='decks.Tag')),
            ],
        ),
    ]
